//
//  Configs.ts
//
//  Generated by Poll Castillo on 09/03/2023.
//
export const Config = {
    tableRows: 50,
    modalRows: 10,
    currentPage: 1,
    offset: 0,
    maxLimitPage: 10,
    isSuperUser: false,
    colorPagination: "rgba(112, 111, 142, 0.16)",
    timeReolad: 30000,
    timeOut: null,
    limitExport: 100,
    idEsmeraldas: "5f13b0bc-95e7-721e-62de-90b58ce56002"
}