//
//  Configs.ts
//
//  Generated by Poll Castillo on 09/03/2023.
//
export const Config = {
    tableRows: 50,
    modalRows: 10,
    currentPage: 1,
    offset: 0,
    maxLimitPage: 10,
    isSuperUser: false,
    colorPagination: "rgba(112, 111, 142, 0.16)",
    timeReolad: 30000,
    timeOut: null,
    limitExport: 100,
    timeOutExport: 200,
    isDepartmentEnabled: function(businessId: any, customerId: any) {
        if (!businessId || !businessId.urlUrb) {
            return false;
        }
        const allowedIds = businessId.urlUrb.split(';');
        return allowedIds.includes(customerId);
    }
}