//d
//  login.ts
//
//  Generated by Poll Castillo on 15/02/2023.
//
import "./config.js"
import { Config } from "./Configs.js"
import { _userAgent, getEntityData, updateEntity, getFilterEntityData, NetliinkBase, basicAuth } from "./endpoints.js"
import { RenderApplicationUI } from "./layout/interface.js"
import { InterfaceElement, Request } from "./types.js"
import { registryPlataform, searchUniversalValue } from "./tools.js"

const loginContainer: InterfaceElement = document.getElementById('login-container')

const connectionHeader = {
    Accept: "application/json",
    "User-agent": _userAgent,
    Authorization: basicAuth,
    "Content-Type": "application/x-www-form-urlencoded",
    Cookie: "JSESSIONID=CDD208A868EAABD1F523BB6F3C8946AF",
}

const consultaUser: string = window.APP_CONFIG.consultaUser

const reqOP: Request = {
    url: `${NetliinkBase}oauth/token`,
    method: 'POST'
}

export class SignIn {
    public async checkSignIn(): Promise<void> {
        const accessToken = localStorage.getItem('access_token')
        const userId = localStorage.getItem('userId')

        const checkUser = async (): Promise<void> => {
            // Limpia sesiones antiguas que guardaron el token temporal de consulta.
            if (userId === consultaUser) {
                this.signOut()
                return
            }

            const currentUsers = await searchUniversalValue('id', '=', `${userId}`, 'User')
            if (currentUsers?.error === 'invalid_token' || !Array.isArray(currentUsers) || currentUsers.length === 0) {
                this.signOut()
                return
            }

            const currentUser = currentUsers[0]
            const customerId: any = localStorage.getItem('customer_id')

            if(currentUser.username === consultaUser){
                this.signOut()
                return
            }
            else{
                if(customerId == null){
                    const user = await getEntityData('User', currentUser.id)
                    if(user.customer?.id != null){
                        await registryPlataform(user.id)
                        localStorage.setItem('customer_id', user.customer.id)
                        window.location.reload()
                        return
                    }else{
                        this.signOut()
                        alert('Usuario no tiene asignado empresa.')
                        return
                    }
                }
                if (currentUser.isSuper !== true) {
                    this.signOut();
                    alert('Usuario no es superusuario.')
                    return
                }
                if (currentUser.userType !== 'CUSTOMER') {
                    this.signOut();
                    alert('Usuario no es tipo cliente.')
                    return
                }
                if (currentUser.verifiedSuper === true) {
                    let user = await getEntityData('User', currentUser.id);
                    let rawCustomer = JSON.stringify({
                        "filter": {
                            "conditions": [
                              {
                                "property": "id",
                                "operator": "=",
                                "value": `${customerId}`
                              },
                              {
                                "property": "business.id",
                                "operator": "=",
                                "value": `${user?.business?.id}`
                              },
                              {
                                "property": "business.state.name",
                                "operator": "=",
                                "value": `Enabled`
                              },
                              {
                                "property": "state.name",
                                "operator": "=",
                                "value": `Enabled`
                              },
                            ]
                        }
                    });
                    let customer = await getFilterEntityData("Customer", rawCustomer);
                    if(user?.state?.name == 'Enabled' && customer.length != 0){
                        new RenderApplicationUI().render();
                    }else{
                        this.signOut();
                        return
                    }
                }else{
                    this.showVerified(currentUser.id, currentUser?.hashSuper)
                }
            }
        }

        if (accessToken) {
            checkUser()
        } else {
            this.showLogin()
            console.info('You need login')
        }

    }

    public showLogin(): void {
        loginContainer.style.display = 'flex !important'
        loginContainer.innerHTML = `
        <div class="login_window">
        <div class="login_header">
          <img src="./public/src/assets/pictures/app_logo.png">
          <h1 class="login_title">Iniciar Sesión</h1>
          <p>Inicie sesión con los datos proporcionados por el proveedor.</p>
        </div>
        <div class="login_content">
          <form id="login-form">
            <div class="input">
              <label for="username">
                <i class="fa-regular fa-user"></i>
              </label>
              <input type="text" id="username"
                placeholder="johndoe@mail.com">
            </div>

            <div class="input">
              <label for="password">
                <i class="fa-regular fa-key"></i>
              </label>
              <input type="password" id="password"
                placeholder="••••••••••••">
            </div>
            <button class="btn btn_primary" id="login">Iniciar Sesión</button>
          </form>
        </div>

        <div class="login_footer">
          <div class="login_icons">
            <i class="fa-regular fa-house"></i>
            <i class="fa-regular fa-user"></i>
            <i class="fa-regular fa-inbox"></i>
            <i class="fa-regular fa-file"></i>
            <i class="fa-regular fa-computer"></i>
            <i class="fa-regular fa-mobile"></i>
          </div>
          <p>Accede a todas nuestras herramientas</p>

          <div class="foot_brief">
            <p>Desarrollado por</p>
            <img src="./public/src/assets/pictures/login_logo.png">
          </div>
        </div>
      </div>
        `
        this.signIn()
    }

    private signIn(): void {
        const form: InterfaceElement = document.querySelector('#login-form')
        const password: InterfaceElement = form.querySelector('#password')
        const userName: InterfaceElement = form.querySelector('#username')
        const trigger: InterfaceElement = form.querySelector('#login')

        trigger.addEventListener('click', async (e: any): Promise<void> => {
            e.preventDefault()

            if (userName.value.trim() == '' || userName.value.trim() == null) {
                console.error('El campo nombre de usuario no puede estar vacío.')
                alert('El campo nombre de usuario no puede estar vacío.')
            }
            else if (password.value.trim() == '' || password.value.trim() == null) {
                console.log('El campo contraseña no puede estar vacío')
                alert('El campo contraseña no puede estar vacío.')
            }
            else {
                await connect(userName.value.trim(), password.value)
            }
        })

        async function requestToken(username: string, userPassword: string): Promise<any> {
            const body = new URLSearchParams({
                grant_type: 'password',
                username,
                password: userPassword
            })
            const reqOptions: RequestInit = {
                method: reqOP.method,
                body: body.toString(),
                headers: connectionHeader
            }

            const response = await fetch(reqOP.url, reqOptions)
            const result = await response.json()

            if (!response.ok || !result.access_token) {
                throw new Error(result.error_description || result.error || 'Bad credentials')
            }

            return result
        }

        async function findUserByEmail(email: string, accessToken: string): Promise<any> {
            const raw = JSON.stringify({
                filter: {
                    conditions: [
                        { property: 'email', operator: '=', value: email },
                        { property: 'state.name', operator: '=', value: 'Enabled' },
                        { property: 'business.state.name', operator: '=', value: 'Enabled' },
                        { property: 'customer.state.name', operator: '=', value: 'Enabled' },
                        { property: 'isSuper', operator: '=', value: true },
                        { property: 'userType', operator: '=', value: 'CUSTOMER' }
                    ]
                },
                limit: 1
            })

            const response = await fetch(`${NetliinkBase}rest/entities/User/search`, {
                method: 'POST',
                headers: {
                    Accept: 'application/json',
                    Authorization: `Bearer ${accessToken}`,
                    'Content-Type': 'application/json'
                },
                body: raw
            })

            if (!response.ok) {
                throw new Error(`No se pudo consultar el usuario (${response.status})`)
            }

            const users = await response.json()
            return users[0]
        }

        async function connect(email: string, userPassword: string): Promise<void> {
            trigger.disabled = true

            try {
                const consultaConnection = await requestToken(consultaUser, consultaUser)
                const user = await findUserByEmail(email, consultaConnection.access_token)

                if (!user?.id || !user?.username) {
                    throw new Error('Bad credentials')
                }

                const userConnection = await requestToken(user.username, userPassword)

                localStorage.removeItem('customer_id')
                localStorage.removeItem('email')
                localStorage.removeItem('password')
                localStorage.setItem('userId', user.id)
                localStorage.setItem('access_token', userConnection.access_token)
                window.location.reload()
            } catch (error) {
                console.error('Error al iniciar sesión:', error)
                alert('Correo o contraseña incorrectos.')
            } finally {
                trigger.disabled = false
            }
        }
    }

    public signOut(): void {
        localStorage.removeItem('access_token')
        localStorage.removeItem('customer_id')
        localStorage.removeItem('email')
        localStorage.removeItem('password')
        localStorage.removeItem('userId')
        // @ts-ignore
        clearTimeout(Config.timeOut);
        this.checkSignIn()
        window.location.reload()
    }

    public showVerified(id: string, hash: string): void {
        loginContainer.style.display = 'flex !important';
        loginContainer.innerHTML = `
        <div class="login_window">
        <div class="login_header">
          <img src="./public/src/assets/pictures/app_logo.png">
          <h1 class="login_title">Verificación de usuario</h1>
          <p>Ingrese el código de verificación enviado al correo.</p>
        </div>
        <div class="login_content">
          <form id="login-form">

            <div class="input">
              <label for="password">
                <i class="fa-regular fa-key"></i>
              </label>
              <input type="password" id="password"
                placeholder="••••••••••••">
            </div>
            <button class="btn btn_close_editor" id="cancel"><i class="fa-regular fa-x"></i></button>
            <button class="btn btn_primary" id="login">Verificar</button>
          </form>
        </div>

        <div class="login_footer">
          <div class="login_icons">
            <i class="fa-regular fa-house"></i>
            <i class="fa-regular fa-user"></i>
            <i class="fa-regular fa-inbox"></i>
            <i class="fa-regular fa-file"></i>
            <i class="fa-regular fa-computer"></i>
            <i class="fa-regular fa-mobile"></i>
          </div>
          <p>Accede a todas nuestras herramientas</p>

          <div class="foot_brief">
            <p>Desarrollado por</p>
            <img src="./public/src/assets/pictures/login_logo.png">
          </div>
        </div>
      </div>
        `
        this.verified(id, hash)
    }
    private verified(id: string, hash: string): void {
        const form: InterfaceElement = document.querySelector('#login-form')
        const password: InterfaceElement = form.querySelector('#password')
        const btnCancel: InterfaceElement = form.querySelector('#cancel')
        const btnVerify: InterfaceElement = form.querySelector('#login')
        btnVerify.addEventListener('click', async(e: any) => {
            e.preventDefault();
            if (password.value.trim() == '' || password.value.trim() == null) {
                console.log('El campo clave no puede estar vacío.')
                alert('El campo clave no puede estar vacío.')
            }
            else {
                if(`${hash}` === `${password.value}`){
                    let updateRaw = JSON.stringify({
                        "verifiedSuper": true
                    });
                    await updateEntity('User', id, updateRaw)
                    .then((res) => {
                        setTimeout(async () => {
                            new RenderApplicationUI().render()
                        }, 100)
                    })
                }else{
                    alert('Código de verificación incorrecto.')
                    this.signOut()
                }
            }
        });
        btnCancel.addEventListener('click', (e: any) => {
            e.preventDefault()
            this.signOut()
        })
    }
}
