//
//  lib.tools.ts
//
// Generated by Poll Castillo on 15/02/2023.
import { currentTime } from "./UserLoggedInfo"
import { getEntitiesData, getUserInfo, getFilterEntityData, getEntityData, registerEntity, _userAgent } from "./endpoints.js"
import { Data, InterfaceElement, InterfaceElementCollection } from "./types.js"

//
export const inputObserver = (): void => {
    const inputs = <NodeListOf<Element>>document.querySelectorAll('input')
    inputs.forEach((input: any) => {
        input.addEventListener("keyup", (e: any): void => {
            if (input.value == "" || input.value == " ")
                input.classList.remove('input_filled'),
                    input.value = ""
            else
                input.classList.add('input_filled')
        })
    })
}

export const inputSelect = async (entity: string, selectId: string, currentStatus?: string): Promise<void> => {
    const data = await getEntitiesData(entity)
    const state = await currentStatus
    const select: InterfaceElement = document.querySelector(`#${selectId}`)
    const inputParent = select.parentNode
    const optionsContent = inputParent.querySelector('#input-options')
    const optionsContainer: InterfaceElement = document.createElement('div')
    optionsContainer.classList.add('input_options_container')

    optionsContent.appendChild(optionsContainer)

    for (let i = 0; i < data.length; i++) {
        const inputOption: InterfaceElement = document.createElement('div')
        select.setAttribute('data-optionid', data[0].id)
        select.setAttribute('value', data[0].name)
        inputOption.classList.add('input_option')
        inputOption.setAttribute('id', data[i].id)
        let nameData: Data = data[i].name
        if (nameData === 'Enabled') {
            nameData = 'Activo'
        } else if (nameData === 'Disabled') {
            nameData = 'Inactivo'
        }
        inputOption.innerHTML = nameData

        optionsContainer.appendChild(inputOption)
    }
    const options: InterfaceElement = optionsContainer.querySelectorAll('.input_option')

    if (state === "Enabled") {
        select.value = "Activo"
        select.setAttribute('data-optionid', '60885987-1b61-4247-94c7-dff348347f93')
    } else if (state === 'Disabled') {
        select.value = "Inactivo"
        select.setAttribute('data-optionid', '225b5e5d-9bb1-469a-b2d9-ca85d53db47b')
    } else {
        select.value = data[0].name
    }

    select.addEventListener('click', (): void => {
        inputParent.classList.toggle('select_active')
    })

    options.forEach((option: any) => {
        option.addEventListener('click', (): void => {
            select.value = option.innerText
            select.removeAttribute('data-optionid')
            select.setAttribute('data-optionid', option.getAttribute('id'))
            inputParent.classList.remove('select_active')
        })
    })
}

export class FixStatusElement {
    public fix(element: any): void {
        const elementTextValue = element.innerText
        if (elementTextValue === "Enabled")
            elementTextValue.innerText = 'Activo',
                elementTextValue.toUpperCase()
        else
            elementTextValue.toUpperCase()
    }
}

export class FixStatusInputElement {
    public fix(inputId: string): void {
        const inputs = <NodeListOf<Element>>document.querySelectorAll(`#${inputId}`)
        inputs.forEach((input: any): void => {
            if (input.value === 'Enabled')
                input.value = 'Activo'.toUpperCase()
            else if (input.value == 'Disabled')
                input.value = 'Inactivo'.toUpperCase()
        })
    }
}

export const drawTagsIntoTables = (): void => {
    const tags: HTMLElement | any = document.querySelectorAll('.tag span')
    tags.forEach((tag: any): void => {
        let text = tag.innerText
        if (text === "Enabled" ||
            text === "enabled" ||
            text === "ENABLED" ||
            text === "Activo" ||
            text === "ACTIVO") {
            tag.innerText = "Activo"
            tag.classList.add("tag_green")
        }
        else if (text === "Disabled" ||
            text === "disabled" ||
            text === "DISABLED" ||
            text === "Inactivo" ||
            text === "INACTIVO") {
            tag.innerText = "Inactivo"
            tag.classList.add("tag_gray")
        } else if (text === "Pendiente" ||
            text === "pendiente" ||
            text === "PENDIENTE") {
            tag.classList.add("tag_yellow")
        }else if(text === "No cumplido"||
            text === "no cumplido" ||
            text === "NO CUMPLIDO"){
            tag.classList.add("tag_red")
        } else {
            tag.classList.add('tag_gray')
        }
    })
}

export class CloseDialog {
    public x(container?: any) {
        container.style.display = 'none'
        // const dialog: InterfaceElement = container.firstElementChild
        // dialog.remove()
    }
}

// SIDEBAR RENDERING TOOLS
export const renderRightSidebar = (UIFragment: InterfaceElement) => {
    const dialogContainer: InterfaceElement = document.getElementById('entity-editor-container')

    dialogContainer.innerHTML = ''
    dialogContainer.style.display = 'flex'
    dialogContainer.innerHTML = UIFragment
}

export const fixDate = () => {
    const arrayDates: InterfaceElementCollection = document.querySelectorAll('#table-date')
    arrayDates.forEach((date: InterfaceElement) => {
        const dateP1 = date.innerText.split('-')
        const dateP2 = dateP1[2].split('T')
        const dateP3 = dateP2[1].split(':')

        const YearDate = dateP1[0]
        const MonthDate = dateP1[1]
        const DayDate = dateP2[0]

        const Hours = dateP3[0]
        const Minutes = dateP3[1]
        const Seconds = dateP3[2]

        const DT = YearDate + ' ' + MonthDate + ' ' + DayDate
        const Time = Hours + ':' + Minutes + ':' + Seconds.slice(0, 2)

        date.innerText = DT + ' ' + Time
    })

}

export class filterDataByHeaderType {
    private readonly datatable: InterfaceElement = document.getElementById('datatable')

    public filter = (): void => {

        this.datatable.onclick = (e: any) => {
            if (e.target.tagName != "SPAN") return
            let span = e.target
            let th = e.target.parentNode

            const THead = this.datatable.querySelectorAll('tr th span')
            THead.forEach((header: InterfaceElement) => {
                header.classList.remove('datatable_header_selected')
            })

            e.target.classList.add('datatable_header_selected')
            this.sortGrid(th.cellIndex, span.dataset.type, span)
        }
    }

    private sortGrid = (colNum: number, type: string, span: any): void => {
        let tbody: any = this.datatable.querySelector('tbody')
        let rowsArray = Array.from(tbody.rows)
        let compare: any

        if(span.dataset.mode == "desc"){              
            compare = (rowA: any, rowB: any) => {
                return rowA.cells[colNum].innerHTML >
                    rowB.cells[colNum].innerHTML ? -1 : 1
            }
            span.setAttribute("data-mode", "asc")
        }else{
            compare = (rowA: any, rowB: any) => {
                return rowA.cells[colNum].innerHTML >
                    rowB.cells[colNum].innerHTML ? 1 : -1
            }
            span.setAttribute("data-mode", "desc")
        }
        /*switch (type) {
            case 'name':
                compare = (rowA: any, rowB: any) => {
                    return rowA.cells[colNum].innerHTML >
                        rowB.cells[colNum].innerHTML ? 1 : -1
                }
                break
            case 'id':
                compare = (rowA: any, rowB: any) => {
                    return rowA.cells[colNum].innerHTML >
                        rowB.cells[colNum].innerHTML ? 1 : -1
                }
                break
            case 'status':
                compare = (rowA: any, rowB: any) => {
                    return rowA.cells[colNum].innerHTML >
                        rowB.cells[colNum].innerHTML ? 1 : -1
                }
                break
            case 'citadel':
                compare = (rowA: any, rowB: any) => {
                    return rowA.cells[colNum].innerHTML >
                        rowB.cells[colNum].innerHTML ? 1 : -1
                }
                break
        }*/

        rowsArray.sort(compare)
        tbody.append(...rowsArray)
    }
}

export const userInfo = getUserInfo()

export const getVerifyEmail = async (email: string) => {
    let value = false;
    //console.log(email.includes("@"))
    if(email.includes("@") === true){
        /*const users = await getEntitiesData('User');
        const data = users.filter((data) => `${data.email}`.includes(`${email}`));*/
        let raw = JSON.stringify({
            "filter": {
                "conditions": [
                  {
                    "property": "email",
                    "operator": "=",
                    "value": `${email}`
                  }
                ]
            }
        });
        let data = await getFilterEntityData("User", raw);
        if(data.length != 0){
            value = true;
        }
    }
    return value;
}

export const getVerifyUsername = async (username: string) => {
    let value = "none";
    //console.log(email.includes("@"))
    if(username != ''){
        /*const users = await getEntitiesData('User');
        const data = users.filter((data) => `${data.email}`.includes(`${email}`));*/
        let raw = JSON.stringify({
            "filter": {
                "conditions": [
                  {
                    "property": "username",
                    "operator": "=",
                    "value": `${username}`
                  }
                ]
            }
        });
        let data = await getFilterEntityData("User", raw);
        if(data.length != 0){
            value = `${verifyUserType(data[0].userType)}, super: ${data[0].isSuper ? 'Si' : 'No'}`;
        }
    }
    return value;
}


export const verifyUserType = (userType: string) =>{
    if(userType == 'CUSTOMER'){
      return 'Cliente'
    }else if(userType == 'GUARD'){
      return 'Guardia'
    }else if(userType == 'EMPLOYEE'){
      return 'Empleado'
    }else if(userType == 'CONTRACTOR'){
      return 'Contratista'
    }else{
      return userType
    }
}

export const registryPlataform = async(id: any) => {
    let platUser = await getEntityData('User', id)
    const _date = new Date()
    // TIME
    const _hours: number = _date.getHours()
    const _minutes: number = _date.getMinutes()
    const _seconds: number = _date.getSeconds()
    const _fixedHours: string = ('0' + _hours).slice(-2)
    const _fixedMinutes: string = ('0' + _minutes).slice(-2)
    const _fixedSeconds: string = ('0' + _seconds).slice(-2)
    const currentTime = `${_fixedHours}:${_fixedMinutes}:${_fixedSeconds}`
    // DATE
    const _day: number = _date.getDate()
    const _month: number = _date.getMonth() + 1
    const _year: number = _date.getFullYear()
    const date: string = `${_year}-${('0' + _month).slice(-2)}-${('0' + _day).slice(-2)}`
    let plataformRaw = JSON.stringify({
        // @ts-ignore
        "userAgent": `${_userAgent}`,
        "customer": {
            "id": `${platUser.customer.id}`
        },
        "system": {
            "id": `3377a344-a1e9-7ea0-4204-44d4040debd2`
        },
        "user": {
            "id": `${platUser.id}`
        },
        // @ts-ignore
        "creationDate": `${date}`,
        // @ts-ignore
        "creationTime": `${currentTime}`,
    })
    await registerEntity(plataformRaw, 'WebAccess')
    .then(res => {
        console.log("Registrado")
    })
}

export const pageNumbers: any = (totalPages: number, max: number, currentPage: number) => {
    let limitMin: any
    let limitMax: any
    let ranges = []
    if(currentPage == 1){
        limitMin = 1
        limitMax = max
        for(let i = limitMin; i <= limitMax; i++){
            ranges.push(i)
        }
    }
    /*else if(currentPage == totalPages){
        let limit = totalPages - max
        for(let i = limit; i <= totalPages; i++){
                ranges.push(i)
        }
    }*/else{
        limitMin = currentPage - 4
        for(let i = limitMin; i < currentPage; i++){
            ranges.push(i)
        }
        limitMax = currentPage + 5
        for(let i = currentPage; i <= limitMax; i++){
            ranges.push(i)
        }
    }
    return ranges
    /*console.log(items)
    console.log("items.length "+items.length)
    console.log("max "+max)
    console.log("currentPage "+currentPage)
    const half: number = Math.round(max/2)
    console.log("half "+half)
    let to = max
    console.log("to "+to)

    console.log("currentPage + half "+(currentPage + half))
    if(currentPage + half >= items.length){
        to = items.length
    } else if(currentPage > half){
        to = currentPage + half
    }
    console.log("to resultado "+to)
    let from = to - max

    return Array.from({length: max}, (_,i) => (i+1)+from)*/
}

export const fillBtnPagination: any = (currentPage: number, color: any) => {
    let btnActive: InterfaceElement = document.getElementById("btnPag"+currentPage)
    if(btnActive) btnActive.style.backgroundColor=color;
    //btnActive.focus();
}

export const currentDateTime = () => {
    const _date = new Date();
    // TIME
    const _hours = _date.getHours();
    const _minutes = _date.getMinutes();
    const _seconds = _date.getSeconds();
    const _fixedHours = ('0' + _hours).slice(-2);
    const _fixedMinutes = ('0' + _minutes).slice(-2);
    const _fixedSeconds = ('0' + _seconds).slice(-2);
    const currentTimeHHMMSS = `${_fixedHours}:${_fixedMinutes}:${_fixedSeconds}`;
    const currentTimeHHMM = `${_fixedHours}:${_fixedMinutes}`;
    // DATE
    const _day = _date.getDate();
    const _month = _date.getMonth() + 1;
    const _year = _date.getFullYear();
    const date = `${_year}-${('0' + _month).slice(-2)}-${('0' + _day).slice(-2)}`;
    return {
        date: date,
        timeHHMMSS: currentTimeHHMMSS,
        timeHHMM: currentTimeHHMM
    }
}

export const calculateGestionMarcation = (assistControl: any) => {
    let objDate: any = {}
    let arrayAssist: any = []
    assistControl.forEach((marcation: any) => {
        // @ts-ignore
        let date = marcation.ingressDate+" "+marcation.user?.username ?? ''
        if (objDate[date]) {
            objDate[date].push(marcation);
        } else {
            objDate[date] = [marcation];
        }
    })
    //console.log(objDate)

    let key = Object.keys(objDate)
    for(let i = 0; i < key.length; i++){
        let objects = objDate[key[i]]
        //console.log(objects)
        //console.log(objects.length)
        let valueMax: any = []
        // @ts-ignore
        objects.map(element => {
            if(element.marcationState.name == 'Finalizado' && (element.egressTime != '' || element.egressTime != null || element.egressTime != undefined)){
                valueMax.push(element)
            }
            
            })
        let maxDate: any = new Date(
            Math.max(
                // @ts-ignore
                ...valueMax.map(element => {
                    return new Date(element.egressDate+" "+element.egressTime);
                }),
            ),
            );
            let minDate = new Date(
            Math.min(
                // @ts-ignore
                ...objects.map(element => {
                return new Date(element.ingressDate+" "+element.ingressTime);
                }),
            ),
            );
            //console.log("max "+maxDate)
            //console.log("min "+minDate)
            const format = (date: any) => {
            var year = date.getFullYear();
            var month = ("0" + (date.getMonth() + 1)).slice(-2);
            var day = ("0" + date.getDate()).slice(-2);

            var hours = ("0" + date.getHours()).slice(-2);
            var minutes = ("0" + date.getMinutes()).slice(-2);
            var seconds = ("0" + date.getSeconds()).slice(-2);
            return `${hours}:${minutes}:${seconds}`
            }
            let fechaSalida = ""
            if(!isNaN(maxDate)) fechaSalida = format(maxDate)
            let obj = {
            "firstName": `${objects[0]?.user?.firstName ?? ''}`,
            "lastName": `${objects[0]?.user?.lastName ?? ''}`,
            "dni": `${objects[0]?.user?.dni ?? ''}`,
            "ingressDate": `${objects[0].ingressDate}`,
            "egressDate": `${
                fechaSalida != "" 
                    ? objects[0].egressDate != undefined ? objects[0].egressDate : objects[0].ingressDate
                    : ""
            }`,
            "ingressTime": `${format(minDate)}`,
            "egressTime": `${fechaSalida}`,
            "username": `${objects[0]?.user?.username ?? ''}`,
        };
        arrayAssist.push(obj);
    }
    return arrayAssist;
}

export const searchUniversalSingle = async (param: any, operator: any, value: any, table: any) => {
    const raw = JSON.stringify({
        "filter": {
          "conditions": [
            {
              "property": `${param}`,
              "operator": `${operator}`,
              "value": `${value}`
            },
          ]
        },
        sort: "-createdDate",
    });
    const data = await getFilterEntityData(`${table}`, raw);
    if(data == undefined || data.length == 0){
        alert(`${param} ${value} no obtenido(a)`);
    }else{
        return data;
    }
}

export const searchUniversalValue = async (param: any, operator: any, value: any, table: any) => {
    const raw = JSON.stringify({
        "filter": {
          "conditions": [
            {
              "property": `${param}`,
              "operator": `${operator}`,
              "value": `${value}`
            },
          ]
        },
        sort: "createdDate",
    });
    const data = await getFilterEntityData(`${table}`, raw);
    if(data == undefined || data.length == 0){
        alert(`${param} ${value} no obtenido(a)`);
    }else{
        return data;
    }
}

export const calculateLine = (text: any, limit: any) => {
    if(text != undefined){
        if(text.length <= limit){
            return text;
        }else{
            return text.slice(0, limit)+"...";
        }
    }else{
        return '';
    }
    
}

// Función para pausar
export const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export const generateFileSimpleXls = (ar: any, title: any, extension: any) => {
  //comprobamos compatibilidad
  if (window.Blob && (window.URL || window.webkitURL)) {
      var contenido = "", d = new Date(), blob, reader, save, clicEvent;
      //creamos contenido del archivo
      for (var i = 0; i < ar.length; i++) {
          //construimos cabecera del csv
          if (i == 0)
              contenido += Object.keys(ar[i]).join(";") + "\n";
          //resto del contenido
          contenido += Object.keys(ar[i]).map(function (key) {
              return ar[i][key];
          }).join(";") + "\n";
      }
      //creamos el blob
      blob = new Blob(["\ufeff", contenido], { type: `text/${extension}` });
      //creamos el reader
      // @ts-ignore
      var reader = new FileReader();
      reader.onload = function (event) {
          //escuchamos su evento load y creamos un enlace en dom
          save = document.createElement('a');
          // @ts-ignore
          save.href = event.target.result;
          save.target = '_blank';
          //aquí le damos nombre al archivo
          save.download = "log_" + title + "_" + d.getDate() + "_" + (d.getMonth() + 1) + "_" + d.getFullYear() + `.${extension}`;
          try {
              //creamos un evento click
              clicEvent = new MouseEvent('click', {
                  'view': window,
                  'bubbles': true,
                  'cancelable': true
              });
          }
          catch (e) {
              //si llega aquí es que probablemente implemente la forma antigua de crear un enlace
              clicEvent = document.createEvent("MouseEvent");
              // @ts-ignore
              clicEvent.click();
          }
          //disparamos el evento
          save.dispatchEvent(clicEvent);
          //liberamos el objeto window.URL
          (window.URL || window.webkitURL).revokeObjectURL(save.href);
      };
      //leemos como url
      reader.readAsDataURL(blob);
  }
  else {
      //el navegador no admite esta opción
      alert("Su navegador no permite esta acción");
  }
};

/**
 * Infiere si un timestamp sin timezone es UTC comparando su hora
 * contra una hora de referencia (ej: creationTime del dispositivo).
 *
 * A diferencia de la versión original, esto NUNCA revienta si los
 * strings vienen mal formados: devuelve un motivo explícito en vez
 * de asumir en silencio.
 *
 * IMPORTANTE: `horaReferencia` se trata SIEMPRE como hora-del-día pura
 * (HH:MM), nunca se le asocia una fecha. Esto es intencional: creationTime
 * solo trae hora, no día. La comparación por aritmética circular
 * (mod 1440) funciona precisamente porque ambos valores son "hora del
 * reloj" y no timestamps completos.
 *
 * Supuesto implícito que esta función NO puede validar por sí sola:
 * `horaReferencia` y `fechaTexto` deben corresponder al mismo instante
 * real (el momento de creación del registro). Si se usa una hora de
 * referencia "actual" para inferir la zona de un timestamp viejo
 * (ej. en un reproceso batch), la inferencia va a ser incorrecta de
 * forma silenciosa, porque no hay información de día para detectarlo.
 */
function inferirZonaOrigen(horaTexto: any, horaReferencia: any, offsetEsperadoMin = 300, margenMin = 15) {
  if (!horaTexto || !horaReferencia) {
    return { esUtc: null, motivo: 'sin_datos_suficientes' };
  }
 
  const parsearHora = (str: any) => {
    const m = String(str).trim().match(/^(\d{1,2}):(\d{2})/);
    if (!m) return null;
    return Number(m[1]) * 60 + Number(m[2]);
  };
 
  const minsA = parsearHora(horaTexto);
  const minsR = parsearHora(horaReferencia);
 
  if (minsA === null || minsR === null) {
    return { esUtc: null, motivo: 'formato_hora_invalido' };
  }
 
  // Diferencia circular (maneja cambio de día)
  const diff = (minsA - minsR + 1440) % 1440;
 
  // Evidencia fuerte de UTC: el diff coincide con el offset esperado (~5h)
  if (Math.abs(diff - offsetEsperadoMin) <= margenMin) {
    return { esUtc: true, motivo: 'coincide_utc', diffMin: diff };
  }
 
  // Evidencia fuerte de que YA es local: el diff está cerca de 0
  // (circular: también cuenta si está cerca de 1440, ej. diff=1439 ~ diff=1)
  const distanciaACero = Math.min(diff, 1440 - diff);
  if (distanciaACero <= margenMin) {
    return { esUtc: false, motivo: 'coincide_local', diffMin: diff };
  }
 
  // Ni una cosa ni la otra: esto NO es evidencia de "es local", es un caso
  // ambiguo. Típicamente ocurre cuando el registro se creó offline en el
  // dispositivo y se sincronizó al servidor mucho después: creationTime y
  // createdDate dejan de representar el mismo instante, y comparar sus
  // horas del día ya no dice nada confiable sobre la zona horaria.
  return { esUtc: null, motivo: 'diff_inesperado_posible_atraso_offline', diffMin: diff };
}
 
function formatearEnZona(fecha: any, zonaHorariaDestino: any) {
  const formateador = new Intl.DateTimeFormat('en-US', {
    timeZone: zonaHorariaDestino,
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit',
    hour12: false,
  });
  const partes = Object.fromEntries(
    formateador.formatToParts(fecha).map(p => [p.type, p.value])
  );
  return `${partes.year}-${partes.month}-${partes.day} ${partes.hour}:${partes.minute}:${partes.second}`;
}
 
/**
 * Formatea una fecha ambigua (sin timezone explícita) a una zona destino,
 * infiriendo el origen mediante una hora de referencia opcional.
 *
 * Mantiene el MISMO contrato de retorno que la versión original:
 *   - string "YYYY-MM-DD HH:mm:ss" si coincide (o no hay referencia)
 *   - string "YYYY-MM-DD HH:mm:ss (Movil: HH:mm)" si no coincide con la referencia
 *   - null si la fecha es inválida o vacía
 *
 * Las mejoras son internas: no crashea con inputs mal formados, la
 * heurística de inferencia queda separada y logueada cuando es ambigua,
 * y ya no hay variables muertas.
 *
 * @param {string} fechaTexto
 * @param {string|null} horaReferencia - ej: "08:47" o "08:47:00"
 * @param {object} [opciones]
 * @param {string} [opciones.zonaHorariaDestino='America/Guayaquil']
 * @param {string} [opciones.offsetOrigenAsumido='-05:00']
 * @param {number} [opciones.offsetEsperadoUtcMin=300]
 * @param {number} [opciones.margenMin=15]
 * @returns {string|null}
 */
export function formatearFechaPorZona(fechaTexto: any, horaReferencia: any = null, opciones: any = {}) {
  const {
    zonaHorariaDestino = 'America/Guayaquil',
    offsetOrigenAsumido = '-05:00',
    offsetEsperadoUtcMin = 300,
    margenMin = 15,
  } = opciones;
 
  try {
    if (!fechaTexto) return null;
 
    let limpio = String(fechaTexto).trim().replace(' ', 'T');
    const tieneZonaExplicita = /[Zz]$|[+-]\d{2}:\d{2}$/.test(limpio);
 
    let inferencia: any = { esUtc: null, motivo: 'zona_explicita' };
 
    if (!tieneZonaExplicita) {
      const horaEnTexto = limpio.split('T')[1];
 
      if (horaReferencia && horaEnTexto) {
        inferencia = inferirZonaOrigen(horaEnTexto, horaReferencia, offsetEsperadoUtcMin, margenMin);
      } else if (!horaReferencia) {
        inferencia = { esUtc: true, motivo: 'sin_referencia_default_utc' };
      } else {
        // Hay horaReferencia pero fechaTexto no trae componente de hora:
        // no hay nada que comparar, se cae a offset local por defecto.
        inferencia = { esUtc: null, motivo: 'fecha_sin_componente_hora' };
      }
 
      if (inferencia.esUtc === null && inferencia.motivo !== 'sin_referencia_default_utc') {
        // Heurística inconclusa (probable atraso offline entre creationTime
        // y createdDate): lo dejamos trazado en vez de asumir en silencio.
        const detalleDiff = inferencia.diffMin != null ? ` (diff=${inferencia.diffMin}min)` : '';
        console.warn(
          `[formatearFechaPorZona] Inferencia ambigua (${inferencia.motivo})${detalleDiff} para "${fechaTexto}" con referencia "${horaReferencia}". Se asume offset local ${offsetOrigenAsumido}, pero podría ser incorrecto.`
        );
      }
 
      limpio += inferencia.esUtc === true ? 'Z' : offsetOrigenAsumido;
    }
 
    const fecha = new Date(limpio);
    if (isNaN(fecha.getTime())) {
      console.error('Dato inválido recibido ->', JSON.stringify(fechaTexto));
      return null;
    }
 
    const resultado = formatearEnZona(fecha, zonaHorariaDestino);
 
    // El paréntesis solo se muestra cuando hubo una conversión UTC
    // confirmada (esUtc === true) y aun así el resultado no coincide con
    // el device. En el caso ambiguo (esUtc === null, posible atraso
    // offline) NO se muestra: ese desfase suele ser comportamiento normal
    // (sync tardío), no un error, y mostrar el mismo paréntesis en ambos
    // casos le quita valor de señal. Queda trazado solo vía console.warn.
    if (inferencia.esUtc === true && horaReferencia) {
      const partesHora = resultado.split(' ')[1];
      const [hRes, mRes] = partesHora.split(':').map(Number);
      const [hR, mR] = String(horaReferencia).trim().slice(0, 5).split(':').map(Number);
 
      if (!Number.isNaN(hR) && !Number.isNaN(mR)) {
        const minsRes = hRes * 60 + mRes;
        const minsR = hR * 60 + mR;
 
        if (Math.abs(minsRes - minsR) <= 5) {
          return resultado;
        }
        return `${resultado} (Movil: ${horaReferencia})`;
      }
    }
 
    return resultado;
 
  } catch (error) {
    console.error('Error crítico:', error);
    return null;
  }
}
 
/* ---------- Ejemplo de uso ---------- */
//
// formatearFechaPorZona('2024-05-10T13:45:00', '08:47');
// => '2024-05-10 08:45:00'   (coincide_utc, diff dentro del margen -> sin sufijo)
//
// formatearFechaPorZona('2024-05-10T13:45:00', '09:10');
// => '2024-05-10 08:45:00 (Movil: 09:10)'   (coincide_utc, pero no coincide con la referencia -> con sufijo)
//
// formatearFechaPorZona('2024-05-10T08:50:00', '08:47');
// => '2024-05-09 13:50:00'   (coincide_local, diff~0 -> ya era hora local, sin sufijo)
//
// formatearFechaPorZona('2024-05-10T20:00:00', '08:47');
// => '2024-05-10 15:00:00'   (diff_inesperado_posible_atraso_offline:
//     sin evidencia confiable de la zona, se asume offset local por defecto,
//     SIN sufijo -> queda trazado solo vía console.warn con el detalle del diff)